import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

export const getByToken = query({
  args: { token: v.string() },
  handler: async (ctx, { token }) => {
    const spin = await ctx.db
      .query("spins")
      .withIndex("by_token", (q) => q.eq("token", token))
      .unique();
    if (!spin) return null;

    return {
      id: spin._id,
      companyId: spin.companyId,
      offerId: spin.offerId ?? null,
      name: spin.name,
      phone: spin.phone,
      token: spin.token ?? null,
      prizeId: spin.prizeId ?? null,
      prizeLabel: spin.prizeLabel ?? null,
      extraFields: spin.extraFields ?? {},
      createdAt: spin.createdAt,
      hasSpun: Boolean(spin.prizeId),
    };
  },
});

// Every registration for a company, newest first, with the offer it came
// through resolved. Instant did the offer join client-side by loading all
// offers; here it is one index read plus a lookup per distinct offer.
export const listByCompany = query({
  args: { companyId: v.id("companies") },
  handler: async (ctx, { companyId }) => {
    const spins = await ctx.db
      .query("spins")
      .withIndex("by_company", (q) => q.eq("companyId", companyId))
      .collect();

    const offers = await ctx.db
      .query("offers")
      .withIndex("by_company", (q) => q.eq("companyId", companyId))
      .collect();
    const byId = new Map(offers.map((o) => [o._id, o]));

    return spins
      .sort((a, b) => b.createdAt - a.createdAt)
      .map((s) => {
        const offer = s.offerId ? byId.get(s.offerId) : undefined;
        return {
          id: s._id,
          name: s.name,
          phone: s.phone,
          prizeLabel: s.prizeLabel ?? null,
          extraFields: s.extraFields ?? {},
          createdAt: s.createdAt,
          offerId: s.offerId ?? null,
          offerTitle: offer?.title ?? null,
          offerType: offer?.type ?? null,
        };
      });
  },
});

// Registration, carrying over registerSpin's exact resolution order:
//   1. a valid magic-link token -> confirm/update that row, same token
//   2. an existing phone for this company -> reuse that row and its token
//   3. otherwise -> a new row
// Returns `created` so the caller knows whether to fire
// registration.created; only case 3 is a genuinely new signup.
//
// The token is generated by the caller: it needs node's randomBytes, which
// Convex's function runtime does not provide.
export const register = mutation({
  args: {
    companyId: v.id("companies"),
    offerId: v.optional(v.id("offers")),
    name: v.string(),
    phone: v.string(),
    extraFields: v.record(v.string(), v.string()),
    // The token to use if a new row (or a token-less existing row) needs one.
    freshToken: v.string(),
    // Present when a returning visitor arrived through a magic link.
    existingToken: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const { companyId, offerId, name, phone, extraFields, freshToken, existingToken } = args;

    if (existingToken) {
      const prior = await ctx.db
        .query("spins")
        .withIndex("by_token", (q) => q.eq("token", existingToken))
        .unique();
      if (prior) {
        await ctx.db.patch(prior._id, { name, phone, extraFields });
        return { id: prior._id, token: existingToken, created: false };
      }
      // Stale or forged token — fall through to the normal flow rather
      // than failing, matching the old behaviour.
    }

    const samePhone = await ctx.db
      .query("spins")
      .withIndex("by_company_phone", (q) => q.eq("companyId", companyId).eq("phone", phone))
      .collect();
    const prev = samePhone[0];

    if (prev) {
      if (prev.token) return { id: prev._id, token: prev.token, created: false };
      await ctx.db.patch(prev._id, { token: freshToken });
      return { id: prev._id, token: freshToken, created: false };
    }

    const createdAt = Date.now();
    const spinId = await ctx.db.insert("spins", {
      companyId,
      offerId,
      name,
      phone,
      token: freshToken,
      extraFields,
      createdAt,
    });
    return { id: spinId, token: freshToken, created: true, createdAt };
  },
});

// The draw, done inside the mutation so it is atomic: the old two-step
// (read prizes, then write the result) let two simultaneous requests on the
// same token both draw. Convex records Math.random, so mutations stay
// deterministic on replay.
export const recordSpin = mutation({
  args: { token: v.string() },
  handler: async (ctx, { token }) => {
    const spin = await ctx.db
      .query("spins")
      .withIndex("by_token", (q) => q.eq("token", token))
      .unique();
    if (!spin) return { status: "not_found" as const };

    if (spin.prizeId) {
      return {
        status: "already" as const,
        prizeId: spin.prizeId,
        prizeLabel: spin.prizeLabel ?? null,
      };
    }

    // Prizes belong to the offer when there is one; the company-level list
    // is the pre-offer fallback.
    const prizes = spin.offerId
      ? await ctx.db
          .query("prizes")
          .withIndex("by_offer", (q) => q.eq("offerId", spin.offerId))
          .collect()
      : await ctx.db
          .query("prizes")
          .withIndex("by_company", (q) => q.eq("companyId", spin.companyId))
          .collect();

    if (prizes.length === 0) return { status: "no_prizes" as const };

    const ordered = prizes.sort((a, b) => a.order - b.order);
    const total = ordered.reduce((sum, p) => sum + p.weight, 0);
    let r = Math.random() * total;
    let chosen = ordered[ordered.length - 1];
    for (const p of ordered) {
      if (r < p.weight) {
        chosen = p;
        break;
      }
      r -= p.weight;
    }

    await ctx.db.patch(spin._id, { prizeId: chosen._id, prizeLabel: chosen.label });

    return {
      status: "drawn" as const,
      prizeId: chosen._id,
      prizeLabel: chosen.label,
      isWin: chosen.isWin,
      registration: {
        id: spin._id,
        name: spin.name,
        phone: spin.phone,
        extraFields: spin.extraFields ?? {},
        createdAt: spin.createdAt,
      },
      companyId: spin.companyId,
      offerId: spin.offerId ?? null,
    };
  },
});

// Backs the social-proof feed: recent wins for one offer.
export const recentWins = query({
  args: { offerId: v.id("offers"), limit: v.number() },
  handler: async (ctx, { offerId, limit }) => {
    const spins = await ctx.db
      .query("spins")
      .withIndex("by_offer", (q) => q.eq("offerId", offerId))
      .collect();

    return spins
      .filter((s) => s.prizeLabel)
      .sort((a, b) => b.createdAt - a.createdAt)
      .slice(0, Math.max(0, limit))
      .map((s) => ({ name: s.name, prizeLabel: s.prizeLabel ?? null, createdAt: s.createdAt }));
  },
});

// Platform-admin view across every company. Deliberately a table-wide
// read with no index: it is not scoped to anything, which is exactly why
// only the admin token can reach it.
export const listAll = query({
  args: {},
  handler: async (ctx) => {
    const spins = await ctx.db.query("spins").order("desc").collect();
    return spins.map((s) => ({
      id: s._id,
      name: s.name,
      phone: s.phone,
      prizeId: s.prizeId ?? null,
      prizeLabel: s.prizeLabel ?? null,
      createdAt: s.createdAt,
    }));
  },
});
